<?php

namespace Bpeh\NestablePageBundle\Entity;

use Bpeh\NestablePageBundle\Entity\Page;
use phpDocumentor\Reflection\Types\Boolean;

/**
 * PageMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageMetaRepository extends \Doctrine\ORM\EntityRepository {

	/**
	 * find page locale and return object or counter
	 *
	 * @param \Bpeh\NestablePageBundle\Entity\Page $page
	 * @param $locale
	 * @param bool $count
	 *
	 * @return mixed
	 */
	public function findPageMetaByLocale( Page $page, $locale, $count = false ) {

		$qb = $this->createQueryBuilder( 'pm' );

		if ( $count ) {
			$qb->select( 'count(pm.id)' );
		}

		$query = $qb->where( 'pm.locale = :locale' )
	      ->andWhere( 'pm.page = :page' )
	      ->setParameter( 'locale', $locale )
	      ->setParameter( 'page', $page )
	      ->getQuery();

		if ( $count ) {
			return $query->getSingleScalarResult();
		}

		return $query->getOneOrNullResult();

	}
}

